// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: light_map.proto

#include "light_map.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_texture_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TextureProto_texture_2eproto;
namespace e8 {
class LightMapProtoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LightMapProto> _instance;
} _LightMapProto_default_instance_;
}  // namespace e8
static void InitDefaultsscc_info_LightMapProto_light_5fmap_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::e8::_LightMapProto_default_instance_;
    new (ptr) ::e8::LightMapProto();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::e8::LightMapProto::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_LightMapProto_light_5fmap_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_LightMapProto_light_5fmap_2eproto}, {
      &scc_info_TextureProto_texture_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_light_5fmap_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_light_5fmap_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_light_5fmap_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_light_5fmap_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::e8::LightMapProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::e8::LightMapProto, id_),
  PROTOBUF_FIELD_OFFSET(::e8::LightMapProto, radiosity_),
  PROTOBUF_FIELD_OFFSET(::e8::LightMapProto, direct_radiosity_),
  PROTOBUF_FIELD_OFFSET(::e8::LightMapProto, indirect_radiosity_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::e8::LightMapProto)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::e8::_LightMapProto_default_instance_),
};

const char descriptor_table_protodef_light_5fmap_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017light_map.proto\022\002e8\032\rtexture.proto\"\232\001\n"
  "\rLightMapProto\022\n\n\002id\030\001 \001(\t\022#\n\tradiosity\030"
  "\002 \001(\0132\020.e8.TextureProto\022*\n\020direct_radios"
  "ity\030\003 \001(\0132\020.e8.TextureProto\022,\n\022indirect_"
  "radiosity\030\004 \001(\0132\020.e8.TextureProtob\006proto"
  "3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_light_5fmap_2eproto_deps[1] = {
  &::descriptor_table_texture_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_light_5fmap_2eproto_sccs[1] = {
  &scc_info_LightMapProto_light_5fmap_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_light_5fmap_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_light_5fmap_2eproto = {
  false, false, descriptor_table_protodef_light_5fmap_2eproto, "light_map.proto", 201,
  &descriptor_table_light_5fmap_2eproto_once, descriptor_table_light_5fmap_2eproto_sccs, descriptor_table_light_5fmap_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_light_5fmap_2eproto::offsets,
  file_level_metadata_light_5fmap_2eproto, 1, file_level_enum_descriptors_light_5fmap_2eproto, file_level_service_descriptors_light_5fmap_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_light_5fmap_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_light_5fmap_2eproto)), true);
namespace e8 {

// ===================================================================

void LightMapProto::InitAsDefaultInstance() {
  ::e8::_LightMapProto_default_instance_._instance.get_mutable()->radiosity_ = const_cast< ::e8::TextureProto*>(
      ::e8::TextureProto::internal_default_instance());
  ::e8::_LightMapProto_default_instance_._instance.get_mutable()->direct_radiosity_ = const_cast< ::e8::TextureProto*>(
      ::e8::TextureProto::internal_default_instance());
  ::e8::_LightMapProto_default_instance_._instance.get_mutable()->indirect_radiosity_ = const_cast< ::e8::TextureProto*>(
      ::e8::TextureProto::internal_default_instance());
}
class LightMapProto::_Internal {
 public:
  static const ::e8::TextureProto& radiosity(const LightMapProto* msg);
  static const ::e8::TextureProto& direct_radiosity(const LightMapProto* msg);
  static const ::e8::TextureProto& indirect_radiosity(const LightMapProto* msg);
};

const ::e8::TextureProto&
LightMapProto::_Internal::radiosity(const LightMapProto* msg) {
  return *msg->radiosity_;
}
const ::e8::TextureProto&
LightMapProto::_Internal::direct_radiosity(const LightMapProto* msg) {
  return *msg->direct_radiosity_;
}
const ::e8::TextureProto&
LightMapProto::_Internal::indirect_radiosity(const LightMapProto* msg) {
  return *msg->indirect_radiosity_;
}
void LightMapProto::clear_radiosity() {
  if (GetArena() == nullptr && radiosity_ != nullptr) {
    delete radiosity_;
  }
  radiosity_ = nullptr;
}
void LightMapProto::clear_direct_radiosity() {
  if (GetArena() == nullptr && direct_radiosity_ != nullptr) {
    delete direct_radiosity_;
  }
  direct_radiosity_ = nullptr;
}
void LightMapProto::clear_indirect_radiosity() {
  if (GetArena() == nullptr && indirect_radiosity_ != nullptr) {
    delete indirect_radiosity_;
  }
  indirect_radiosity_ = nullptr;
}
LightMapProto::LightMapProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:e8.LightMapProto)
}
LightMapProto::LightMapProto(const LightMapProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_id().empty()) {
    id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_id(),
      GetArena());
  }
  if (from._internal_has_radiosity()) {
    radiosity_ = new ::e8::TextureProto(*from.radiosity_);
  } else {
    radiosity_ = nullptr;
  }
  if (from._internal_has_direct_radiosity()) {
    direct_radiosity_ = new ::e8::TextureProto(*from.direct_radiosity_);
  } else {
    direct_radiosity_ = nullptr;
  }
  if (from._internal_has_indirect_radiosity()) {
    indirect_radiosity_ = new ::e8::TextureProto(*from.indirect_radiosity_);
  } else {
    indirect_radiosity_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:e8.LightMapProto)
}

void LightMapProto::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_LightMapProto_light_5fmap_2eproto.base);
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&radiosity_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&indirect_radiosity_) -
      reinterpret_cast<char*>(&radiosity_)) + sizeof(indirect_radiosity_));
}

LightMapProto::~LightMapProto() {
  // @@protoc_insertion_point(destructor:e8.LightMapProto)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void LightMapProto::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete radiosity_;
  if (this != internal_default_instance()) delete direct_radiosity_;
  if (this != internal_default_instance()) delete indirect_radiosity_;
}

void LightMapProto::ArenaDtor(void* object) {
  LightMapProto* _this = reinterpret_cast< LightMapProto* >(object);
  (void)_this;
}
void LightMapProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LightMapProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LightMapProto& LightMapProto::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LightMapProto_light_5fmap_2eproto.base);
  return *internal_default_instance();
}


void LightMapProto::Clear() {
// @@protoc_insertion_point(message_clear_start:e8.LightMapProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && radiosity_ != nullptr) {
    delete radiosity_;
  }
  radiosity_ = nullptr;
  if (GetArena() == nullptr && direct_radiosity_ != nullptr) {
    delete direct_radiosity_;
  }
  direct_radiosity_ = nullptr;
  if (GetArena() == nullptr && indirect_radiosity_ != nullptr) {
    delete indirect_radiosity_;
  }
  indirect_radiosity_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LightMapProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "e8.LightMapProto.id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .e8.TextureProto radiosity = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_radiosity(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .e8.TextureProto direct_radiosity = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_direct_radiosity(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .e8.TextureProto indirect_radiosity = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_indirect_radiosity(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* LightMapProto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:e8.LightMapProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (this->id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "e8.LightMapProto.id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  // .e8.TextureProto radiosity = 2;
  if (this->has_radiosity()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::radiosity(this), target, stream);
  }

  // .e8.TextureProto direct_radiosity = 3;
  if (this->has_direct_radiosity()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::direct_radiosity(this), target, stream);
  }

  // .e8.TextureProto indirect_radiosity = 4;
  if (this->has_indirect_radiosity()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::indirect_radiosity(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:e8.LightMapProto)
  return target;
}

size_t LightMapProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:e8.LightMapProto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // .e8.TextureProto radiosity = 2;
  if (this->has_radiosity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *radiosity_);
  }

  // .e8.TextureProto direct_radiosity = 3;
  if (this->has_direct_radiosity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *direct_radiosity_);
  }

  // .e8.TextureProto indirect_radiosity = 4;
  if (this->has_indirect_radiosity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *indirect_radiosity_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LightMapProto::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:e8.LightMapProto)
  GOOGLE_DCHECK_NE(&from, this);
  const LightMapProto* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LightMapProto>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:e8.LightMapProto)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:e8.LightMapProto)
    MergeFrom(*source);
  }
}

void LightMapProto::MergeFrom(const LightMapProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:e8.LightMapProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id().size() > 0) {
    _internal_set_id(from._internal_id());
  }
  if (from.has_radiosity()) {
    _internal_mutable_radiosity()->::e8::TextureProto::MergeFrom(from._internal_radiosity());
  }
  if (from.has_direct_radiosity()) {
    _internal_mutable_direct_radiosity()->::e8::TextureProto::MergeFrom(from._internal_direct_radiosity());
  }
  if (from.has_indirect_radiosity()) {
    _internal_mutable_indirect_radiosity()->::e8::TextureProto::MergeFrom(from._internal_indirect_radiosity());
  }
}

void LightMapProto::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:e8.LightMapProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LightMapProto::CopyFrom(const LightMapProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:e8.LightMapProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LightMapProto::IsInitialized() const {
  return true;
}

void LightMapProto::InternalSwap(LightMapProto* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  id_.Swap(&other->id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LightMapProto, indirect_radiosity_)
      + sizeof(LightMapProto::indirect_radiosity_)
      - PROTOBUF_FIELD_OFFSET(LightMapProto, radiosity_)>(
          reinterpret_cast<char*>(&radiosity_),
          reinterpret_cast<char*>(&other->radiosity_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LightMapProto::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace e8
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::e8::LightMapProto* Arena::CreateMaybeMessage< ::e8::LightMapProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::e8::LightMapProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
