// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geometry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_geometry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_geometry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "primitive.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_geometry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_geometry_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_geometry_2eproto;
namespace e8 {
class Geometry;
class GeometryDefaultTypeInternal;
extern GeometryDefaultTypeInternal _Geometry_default_instance_;
class GeometryLod;
class GeometryLodDefaultTypeInternal;
extern GeometryLodDefaultTypeInternal _GeometryLod_default_instance_;
}  // namespace e8
PROTOBUF_NAMESPACE_OPEN
template<> ::e8::Geometry* Arena::CreateMaybeMessage<::e8::Geometry>(Arena*);
template<> ::e8::GeometryLod* Arena::CreateMaybeMessage<::e8::GeometryLod>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace e8 {

enum Geometry_RigidityType : int {
  Geometry_RigidityType_INVALID = 0,
  Geometry_RigidityType_STATIC = 1,
  Geometry_RigidityType_RIGID = 2,
  Geometry_RigidityType_DEFORMABLE = 3,
  Geometry_RigidityType_TEARABLE = 4,
  Geometry_RigidityType_Geometry_RigidityType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Geometry_RigidityType_Geometry_RigidityType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Geometry_RigidityType_IsValid(int value);
constexpr Geometry_RigidityType Geometry_RigidityType_RigidityType_MIN = Geometry_RigidityType_INVALID;
constexpr Geometry_RigidityType Geometry_RigidityType_RigidityType_MAX = Geometry_RigidityType_TEARABLE;
constexpr int Geometry_RigidityType_RigidityType_ARRAYSIZE = Geometry_RigidityType_RigidityType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Geometry_RigidityType_descriptor();
template<typename T>
inline const std::string& Geometry_RigidityType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Geometry_RigidityType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Geometry_RigidityType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Geometry_RigidityType_descriptor(), enum_t_value);
}
inline bool Geometry_RigidityType_Parse(
    const std::string& name, Geometry_RigidityType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Geometry_RigidityType>(
    Geometry_RigidityType_descriptor(), name, value);
}
// ===================================================================

class Geometry PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:e8.Geometry) */ {
 public:
  inline Geometry() : Geometry(nullptr) {};
  virtual ~Geometry();

  Geometry(const Geometry& from);
  Geometry(Geometry&& from) noexcept
    : Geometry() {
    *this = ::std::move(from);
  }

  inline Geometry& operator=(const Geometry& from) {
    CopyFrom(from);
    return *this;
  }
  inline Geometry& operator=(Geometry&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Geometry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Geometry* internal_default_instance() {
    return reinterpret_cast<const Geometry*>(
               &_Geometry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Geometry& a, Geometry& b) {
    a.Swap(&b);
  }
  inline void Swap(Geometry* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Geometry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Geometry* New() const final {
    return CreateMaybeMessage<Geometry>(nullptr);
  }

  Geometry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Geometry>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Geometry& from);
  void MergeFrom(const Geometry& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Geometry* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "e8.Geometry";
  }
  protected:
  explicit Geometry(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_geometry_2eproto);
    return ::descriptor_table_geometry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Geometry_RigidityType RigidityType;
  static constexpr RigidityType INVALID =
    Geometry_RigidityType_INVALID;
  static constexpr RigidityType STATIC =
    Geometry_RigidityType_STATIC;
  static constexpr RigidityType RIGID =
    Geometry_RigidityType_RIGID;
  static constexpr RigidityType DEFORMABLE =
    Geometry_RigidityType_DEFORMABLE;
  static constexpr RigidityType TEARABLE =
    Geometry_RigidityType_TEARABLE;
  static inline bool RigidityType_IsValid(int value) {
    return Geometry_RigidityType_IsValid(value);
  }
  static constexpr RigidityType RigidityType_MIN =
    Geometry_RigidityType_RigidityType_MIN;
  static constexpr RigidityType RigidityType_MAX =
    Geometry_RigidityType_RigidityType_MAX;
  static constexpr int RigidityType_ARRAYSIZE =
    Geometry_RigidityType_RigidityType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  RigidityType_descriptor() {
    return Geometry_RigidityType_descriptor();
  }
  template<typename T>
  static inline const std::string& RigidityType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, RigidityType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function RigidityType_Name.");
    return Geometry_RigidityType_Name(enum_t_value);
  }
  static inline bool RigidityType_Parse(const std::string& name,
      RigidityType* value) {
    return Geometry_RigidityType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kVerticesFieldNumber = 2,
    kPrimitivesFieldNumber = 3,
    kRigidityFieldNumber = 1,
  };
  // repeated .e8.PrimitiveVertex vertices = 2;
  int vertices_size() const;
  private:
  int _internal_vertices_size() const;
  public:
  void clear_vertices();
  ::e8::PrimitiveVertex* mutable_vertices(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::PrimitiveVertex >*
      mutable_vertices();
  private:
  const ::e8::PrimitiveVertex& _internal_vertices(int index) const;
  ::e8::PrimitiveVertex* _internal_add_vertices();
  public:
  const ::e8::PrimitiveVertex& vertices(int index) const;
  ::e8::PrimitiveVertex* add_vertices();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::PrimitiveVertex >&
      vertices() const;

  // repeated .e8.PrimitiveIndices primitives = 3;
  int primitives_size() const;
  private:
  int _internal_primitives_size() const;
  public:
  void clear_primitives();
  ::e8::PrimitiveIndices* mutable_primitives(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::PrimitiveIndices >*
      mutable_primitives();
  private:
  const ::e8::PrimitiveIndices& _internal_primitives(int index) const;
  ::e8::PrimitiveIndices* _internal_add_primitives();
  public:
  const ::e8::PrimitiveIndices& primitives(int index) const;
  ::e8::PrimitiveIndices* add_primitives();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::PrimitiveIndices >&
      primitives() const;

  // .e8.Geometry.RigidityType rigidity = 1;
  void clear_rigidity();
  ::e8::Geometry_RigidityType rigidity() const;
  void set_rigidity(::e8::Geometry_RigidityType value);
  private:
  ::e8::Geometry_RigidityType _internal_rigidity() const;
  void _internal_set_rigidity(::e8::Geometry_RigidityType value);
  public:

  // @@protoc_insertion_point(class_scope:e8.Geometry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::PrimitiveVertex > vertices_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::PrimitiveIndices > primitives_;
  int rigidity_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_geometry_2eproto;
};
// -------------------------------------------------------------------

class GeometryLod PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:e8.GeometryLod) */ {
 public:
  inline GeometryLod() : GeometryLod(nullptr) {};
  virtual ~GeometryLod();

  GeometryLod(const GeometryLod& from);
  GeometryLod(GeometryLod&& from) noexcept
    : GeometryLod() {
    *this = ::std::move(from);
  }

  inline GeometryLod& operator=(const GeometryLod& from) {
    CopyFrom(from);
    return *this;
  }
  inline GeometryLod& operator=(GeometryLod&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GeometryLod& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GeometryLod* internal_default_instance() {
    return reinterpret_cast<const GeometryLod*>(
               &_GeometryLod_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GeometryLod& a, GeometryLod& b) {
    a.Swap(&b);
  }
  inline void Swap(GeometryLod* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GeometryLod* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GeometryLod* New() const final {
    return CreateMaybeMessage<GeometryLod>(nullptr);
  }

  GeometryLod* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GeometryLod>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GeometryLod& from);
  void MergeFrom(const GeometryLod& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GeometryLod* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "e8.GeometryLod";
  }
  protected:
  explicit GeometryLod(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_geometry_2eproto);
    return ::descriptor_table_geometry_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGeometryLodFieldNumber = 3,
    kMinDistancesFieldNumber = 4,
    kIdFieldNumber = 1,
    kNameFieldNumber = 2,
  };
  // repeated .e8.Geometry geometry_lod = 3;
  int geometry_lod_size() const;
  private:
  int _internal_geometry_lod_size() const;
  public:
  void clear_geometry_lod();
  ::e8::Geometry* mutable_geometry_lod(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::Geometry >*
      mutable_geometry_lod();
  private:
  const ::e8::Geometry& _internal_geometry_lod(int index) const;
  ::e8::Geometry* _internal_add_geometry_lod();
  public:
  const ::e8::Geometry& geometry_lod(int index) const;
  ::e8::Geometry* add_geometry_lod();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::Geometry >&
      geometry_lod() const;

  // repeated float min_distances = 4;
  int min_distances_size() const;
  private:
  int _internal_min_distances_size() const;
  public:
  void clear_min_distances();
  private:
  float _internal_min_distances(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_min_distances() const;
  void _internal_add_min_distances(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_min_distances();
  public:
  float min_distances(int index) const;
  void set_min_distances(int index, float value);
  void add_min_distances(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      min_distances() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_min_distances();

  // string id = 1;
  void clear_id();
  const std::string& id() const;
  void set_id(const std::string& value);
  void set_id(std::string&& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  std::string* mutable_id();
  std::string* release_id();
  void set_allocated_id(std::string* id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_id(
      std::string* id);
  private:
  const std::string& _internal_id() const;
  void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:e8.GeometryLod)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::Geometry > geometry_lod_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > min_distances_;
  mutable std::atomic<int> _min_distances_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_geometry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Geometry

// .e8.Geometry.RigidityType rigidity = 1;
inline void Geometry::clear_rigidity() {
  rigidity_ = 0;
}
inline ::e8::Geometry_RigidityType Geometry::_internal_rigidity() const {
  return static_cast< ::e8::Geometry_RigidityType >(rigidity_);
}
inline ::e8::Geometry_RigidityType Geometry::rigidity() const {
  // @@protoc_insertion_point(field_get:e8.Geometry.rigidity)
  return _internal_rigidity();
}
inline void Geometry::_internal_set_rigidity(::e8::Geometry_RigidityType value) {
  
  rigidity_ = value;
}
inline void Geometry::set_rigidity(::e8::Geometry_RigidityType value) {
  _internal_set_rigidity(value);
  // @@protoc_insertion_point(field_set:e8.Geometry.rigidity)
}

// repeated .e8.PrimitiveVertex vertices = 2;
inline int Geometry::_internal_vertices_size() const {
  return vertices_.size();
}
inline int Geometry::vertices_size() const {
  return _internal_vertices_size();
}
inline ::e8::PrimitiveVertex* Geometry::mutable_vertices(int index) {
  // @@protoc_insertion_point(field_mutable:e8.Geometry.vertices)
  return vertices_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::PrimitiveVertex >*
Geometry::mutable_vertices() {
  // @@protoc_insertion_point(field_mutable_list:e8.Geometry.vertices)
  return &vertices_;
}
inline const ::e8::PrimitiveVertex& Geometry::_internal_vertices(int index) const {
  return vertices_.Get(index);
}
inline const ::e8::PrimitiveVertex& Geometry::vertices(int index) const {
  // @@protoc_insertion_point(field_get:e8.Geometry.vertices)
  return _internal_vertices(index);
}
inline ::e8::PrimitiveVertex* Geometry::_internal_add_vertices() {
  return vertices_.Add();
}
inline ::e8::PrimitiveVertex* Geometry::add_vertices() {
  // @@protoc_insertion_point(field_add:e8.Geometry.vertices)
  return _internal_add_vertices();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::PrimitiveVertex >&
Geometry::vertices() const {
  // @@protoc_insertion_point(field_list:e8.Geometry.vertices)
  return vertices_;
}

// repeated .e8.PrimitiveIndices primitives = 3;
inline int Geometry::_internal_primitives_size() const {
  return primitives_.size();
}
inline int Geometry::primitives_size() const {
  return _internal_primitives_size();
}
inline ::e8::PrimitiveIndices* Geometry::mutable_primitives(int index) {
  // @@protoc_insertion_point(field_mutable:e8.Geometry.primitives)
  return primitives_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::PrimitiveIndices >*
Geometry::mutable_primitives() {
  // @@protoc_insertion_point(field_mutable_list:e8.Geometry.primitives)
  return &primitives_;
}
inline const ::e8::PrimitiveIndices& Geometry::_internal_primitives(int index) const {
  return primitives_.Get(index);
}
inline const ::e8::PrimitiveIndices& Geometry::primitives(int index) const {
  // @@protoc_insertion_point(field_get:e8.Geometry.primitives)
  return _internal_primitives(index);
}
inline ::e8::PrimitiveIndices* Geometry::_internal_add_primitives() {
  return primitives_.Add();
}
inline ::e8::PrimitiveIndices* Geometry::add_primitives() {
  // @@protoc_insertion_point(field_add:e8.Geometry.primitives)
  return _internal_add_primitives();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::PrimitiveIndices >&
Geometry::primitives() const {
  // @@protoc_insertion_point(field_list:e8.Geometry.primitives)
  return primitives_;
}

// -------------------------------------------------------------------

// GeometryLod

// string id = 1;
inline void GeometryLod::clear_id() {
  id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GeometryLod::id() const {
  // @@protoc_insertion_point(field_get:e8.GeometryLod.id)
  return _internal_id();
}
inline void GeometryLod::set_id(const std::string& value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:e8.GeometryLod.id)
}
inline std::string* GeometryLod::mutable_id() {
  // @@protoc_insertion_point(field_mutable:e8.GeometryLod.id)
  return _internal_mutable_id();
}
inline const std::string& GeometryLod::_internal_id() const {
  return id_.Get();
}
inline void GeometryLod::_internal_set_id(const std::string& value) {
  
  id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GeometryLod::set_id(std::string&& value) {
  
  id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:e8.GeometryLod.id)
}
inline void GeometryLod::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:e8.GeometryLod.id)
}
inline void GeometryLod::set_id(const char* value,
    size_t size) {
  
  id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:e8.GeometryLod.id)
}
inline std::string* GeometryLod::_internal_mutable_id() {
  
  return id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GeometryLod::release_id() {
  // @@protoc_insertion_point(field_release:e8.GeometryLod.id)
  return id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GeometryLod::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:e8.GeometryLod.id)
}
inline std::string* GeometryLod::unsafe_arena_release_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:e8.GeometryLod.id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void GeometryLod::unsafe_arena_set_allocated_id(
    std::string* id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (id != nullptr) {
    
  } else {
    
  }
  id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:e8.GeometryLod.id)
}

// string name = 2;
inline void GeometryLod::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GeometryLod::name() const {
  // @@protoc_insertion_point(field_get:e8.GeometryLod.name)
  return _internal_name();
}
inline void GeometryLod::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:e8.GeometryLod.name)
}
inline std::string* GeometryLod::mutable_name() {
  // @@protoc_insertion_point(field_mutable:e8.GeometryLod.name)
  return _internal_mutable_name();
}
inline const std::string& GeometryLod::_internal_name() const {
  return name_.Get();
}
inline void GeometryLod::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GeometryLod::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:e8.GeometryLod.name)
}
inline void GeometryLod::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:e8.GeometryLod.name)
}
inline void GeometryLod::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:e8.GeometryLod.name)
}
inline std::string* GeometryLod::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GeometryLod::release_name() {
  // @@protoc_insertion_point(field_release:e8.GeometryLod.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GeometryLod::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:e8.GeometryLod.name)
}
inline std::string* GeometryLod::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:e8.GeometryLod.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void GeometryLod::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:e8.GeometryLod.name)
}

// repeated .e8.Geometry geometry_lod = 3;
inline int GeometryLod::_internal_geometry_lod_size() const {
  return geometry_lod_.size();
}
inline int GeometryLod::geometry_lod_size() const {
  return _internal_geometry_lod_size();
}
inline void GeometryLod::clear_geometry_lod() {
  geometry_lod_.Clear();
}
inline ::e8::Geometry* GeometryLod::mutable_geometry_lod(int index) {
  // @@protoc_insertion_point(field_mutable:e8.GeometryLod.geometry_lod)
  return geometry_lod_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::Geometry >*
GeometryLod::mutable_geometry_lod() {
  // @@protoc_insertion_point(field_mutable_list:e8.GeometryLod.geometry_lod)
  return &geometry_lod_;
}
inline const ::e8::Geometry& GeometryLod::_internal_geometry_lod(int index) const {
  return geometry_lod_.Get(index);
}
inline const ::e8::Geometry& GeometryLod::geometry_lod(int index) const {
  // @@protoc_insertion_point(field_get:e8.GeometryLod.geometry_lod)
  return _internal_geometry_lod(index);
}
inline ::e8::Geometry* GeometryLod::_internal_add_geometry_lod() {
  return geometry_lod_.Add();
}
inline ::e8::Geometry* GeometryLod::add_geometry_lod() {
  // @@protoc_insertion_point(field_add:e8.GeometryLod.geometry_lod)
  return _internal_add_geometry_lod();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::Geometry >&
GeometryLod::geometry_lod() const {
  // @@protoc_insertion_point(field_list:e8.GeometryLod.geometry_lod)
  return geometry_lod_;
}

// repeated float min_distances = 4;
inline int GeometryLod::_internal_min_distances_size() const {
  return min_distances_.size();
}
inline int GeometryLod::min_distances_size() const {
  return _internal_min_distances_size();
}
inline void GeometryLod::clear_min_distances() {
  min_distances_.Clear();
}
inline float GeometryLod::_internal_min_distances(int index) const {
  return min_distances_.Get(index);
}
inline float GeometryLod::min_distances(int index) const {
  // @@protoc_insertion_point(field_get:e8.GeometryLod.min_distances)
  return _internal_min_distances(index);
}
inline void GeometryLod::set_min_distances(int index, float value) {
  min_distances_.Set(index, value);
  // @@protoc_insertion_point(field_set:e8.GeometryLod.min_distances)
}
inline void GeometryLod::_internal_add_min_distances(float value) {
  min_distances_.Add(value);
}
inline void GeometryLod::add_min_distances(float value) {
  _internal_add_min_distances(value);
  // @@protoc_insertion_point(field_add:e8.GeometryLod.min_distances)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
GeometryLod::_internal_min_distances() const {
  return min_distances_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
GeometryLod::min_distances() const {
  // @@protoc_insertion_point(field_list:e8.GeometryLod.min_distances)
  return _internal_min_distances();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
GeometryLod::_internal_mutable_min_distances() {
  return &min_distances_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
GeometryLod::mutable_min_distances() {
  // @@protoc_insertion_point(field_mutable_list:e8.GeometryLod.min_distances)
  return _internal_mutable_min_distances();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace e8

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::e8::Geometry_RigidityType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::e8::Geometry_RigidityType>() {
  return ::e8::Geometry_RigidityType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_geometry_2eproto
