// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: procedural_object.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_procedural_5fobject_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_procedural_5fobject_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "procedural_shape.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_procedural_5fobject_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_procedural_5fobject_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_procedural_5fobject_2eproto;
namespace e8 {
class ProceduralObjectProto;
class ProceduralObjectProtoDefaultTypeInternal;
extern ProceduralObjectProtoDefaultTypeInternal _ProceduralObjectProto_default_instance_;
}  // namespace e8
PROTOBUF_NAMESPACE_OPEN
template<> ::e8::ProceduralObjectProto* Arena::CreateMaybeMessage<::e8::ProceduralObjectProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace e8 {

enum ProceduralObjectProto_ProceduralObjectType : int {
  ProceduralObjectProto_ProceduralObjectType_INVALID = 0,
  ProceduralObjectProto_ProceduralObjectType_PLANE = 1,
  ProceduralObjectProto_ProceduralObjectType_BOX = 2,
  ProceduralObjectProto_ProceduralObjectType_SPHERE = 3,
  ProceduralObjectProto_ProceduralObjectType_ProceduralObjectProto_ProceduralObjectType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ProceduralObjectProto_ProceduralObjectType_ProceduralObjectProto_ProceduralObjectType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ProceduralObjectProto_ProceduralObjectType_IsValid(int value);
constexpr ProceduralObjectProto_ProceduralObjectType ProceduralObjectProto_ProceduralObjectType_ProceduralObjectType_MIN = ProceduralObjectProto_ProceduralObjectType_INVALID;
constexpr ProceduralObjectProto_ProceduralObjectType ProceduralObjectProto_ProceduralObjectType_ProceduralObjectType_MAX = ProceduralObjectProto_ProceduralObjectType_SPHERE;
constexpr int ProceduralObjectProto_ProceduralObjectType_ProceduralObjectType_ARRAYSIZE = ProceduralObjectProto_ProceduralObjectType_ProceduralObjectType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ProceduralObjectProto_ProceduralObjectType_descriptor();
template<typename T>
inline const std::string& ProceduralObjectProto_ProceduralObjectType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ProceduralObjectProto_ProceduralObjectType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ProceduralObjectProto_ProceduralObjectType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ProceduralObjectProto_ProceduralObjectType_descriptor(), enum_t_value);
}
inline bool ProceduralObjectProto_ProceduralObjectType_Parse(
    const std::string& name, ProceduralObjectProto_ProceduralObjectType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ProceduralObjectProto_ProceduralObjectType>(
    ProceduralObjectProto_ProceduralObjectType_descriptor(), name, value);
}
// ===================================================================

class ProceduralObjectProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:e8.ProceduralObjectProto) */ {
 public:
  inline ProceduralObjectProto() : ProceduralObjectProto(nullptr) {};
  virtual ~ProceduralObjectProto();

  ProceduralObjectProto(const ProceduralObjectProto& from);
  ProceduralObjectProto(ProceduralObjectProto&& from) noexcept
    : ProceduralObjectProto() {
    *this = ::std::move(from);
  }

  inline ProceduralObjectProto& operator=(const ProceduralObjectProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProceduralObjectProto& operator=(ProceduralObjectProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ProceduralObjectProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProceduralObjectProto* internal_default_instance() {
    return reinterpret_cast<const ProceduralObjectProto*>(
               &_ProceduralObjectProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ProceduralObjectProto& a, ProceduralObjectProto& b) {
    a.Swap(&b);
  }
  inline void Swap(ProceduralObjectProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProceduralObjectProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ProceduralObjectProto* New() const final {
    return CreateMaybeMessage<ProceduralObjectProto>(nullptr);
  }

  ProceduralObjectProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ProceduralObjectProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ProceduralObjectProto& from);
  void MergeFrom(const ProceduralObjectProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProceduralObjectProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "e8.ProceduralObjectProto";
  }
  protected:
  explicit ProceduralObjectProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_procedural_5fobject_2eproto);
    return ::descriptor_table_procedural_5fobject_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef ProceduralObjectProto_ProceduralObjectType ProceduralObjectType;
  static constexpr ProceduralObjectType INVALID =
    ProceduralObjectProto_ProceduralObjectType_INVALID;
  static constexpr ProceduralObjectType PLANE =
    ProceduralObjectProto_ProceduralObjectType_PLANE;
  static constexpr ProceduralObjectType BOX =
    ProceduralObjectProto_ProceduralObjectType_BOX;
  static constexpr ProceduralObjectType SPHERE =
    ProceduralObjectProto_ProceduralObjectType_SPHERE;
  static inline bool ProceduralObjectType_IsValid(int value) {
    return ProceduralObjectProto_ProceduralObjectType_IsValid(value);
  }
  static constexpr ProceduralObjectType ProceduralObjectType_MIN =
    ProceduralObjectProto_ProceduralObjectType_ProceduralObjectType_MIN;
  static constexpr ProceduralObjectType ProceduralObjectType_MAX =
    ProceduralObjectProto_ProceduralObjectType_ProceduralObjectType_MAX;
  static constexpr int ProceduralObjectType_ARRAYSIZE =
    ProceduralObjectProto_ProceduralObjectType_ProceduralObjectType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ProceduralObjectType_descriptor() {
    return ProceduralObjectProto_ProceduralObjectType_descriptor();
  }
  template<typename T>
  static inline const std::string& ProceduralObjectType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ProceduralObjectType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ProceduralObjectType_Name.");
    return ProceduralObjectProto_ProceduralObjectType_Name(enum_t_value);
  }
  static inline bool ProceduralObjectType_Parse(const std::string& name,
      ProceduralObjectType* value) {
    return ProceduralObjectProto_ProceduralObjectType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kShapesFieldNumber = 5,
    kIdFieldNumber = 1,
    kNameFieldNumber = 2,
    kTypeFieldNumber = 3,
    kMovableFieldNumber = 4,
  };
  // repeated .e8.ProceduralShapeProto shapes = 5;
  int shapes_size() const;
  private:
  int _internal_shapes_size() const;
  public:
  void clear_shapes();
  ::e8::ProceduralShapeProto* mutable_shapes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::ProceduralShapeProto >*
      mutable_shapes();
  private:
  const ::e8::ProceduralShapeProto& _internal_shapes(int index) const;
  ::e8::ProceduralShapeProto* _internal_add_shapes();
  public:
  const ::e8::ProceduralShapeProto& shapes(int index) const;
  ::e8::ProceduralShapeProto* add_shapes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::ProceduralShapeProto >&
      shapes() const;

  // string id = 1;
  void clear_id();
  const std::string& id() const;
  void set_id(const std::string& value);
  void set_id(std::string&& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  std::string* mutable_id();
  std::string* release_id();
  void set_allocated_id(std::string* id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_id(
      std::string* id);
  private:
  const std::string& _internal_id() const;
  void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .e8.ProceduralObjectProto.ProceduralObjectType type = 3;
  void clear_type();
  ::e8::ProceduralObjectProto_ProceduralObjectType type() const;
  void set_type(::e8::ProceduralObjectProto_ProceduralObjectType value);
  private:
  ::e8::ProceduralObjectProto_ProceduralObjectType _internal_type() const;
  void _internal_set_type(::e8::ProceduralObjectProto_ProceduralObjectType value);
  public:

  // bool movable = 4;
  void clear_movable();
  bool movable() const;
  void set_movable(bool value);
  private:
  bool _internal_movable() const;
  void _internal_set_movable(bool value);
  public:

  // @@protoc_insertion_point(class_scope:e8.ProceduralObjectProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::ProceduralShapeProto > shapes_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  int type_;
  bool movable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_procedural_5fobject_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProceduralObjectProto

// string id = 1;
inline void ProceduralObjectProto::clear_id() {
  id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ProceduralObjectProto::id() const {
  // @@protoc_insertion_point(field_get:e8.ProceduralObjectProto.id)
  return _internal_id();
}
inline void ProceduralObjectProto::set_id(const std::string& value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:e8.ProceduralObjectProto.id)
}
inline std::string* ProceduralObjectProto::mutable_id() {
  // @@protoc_insertion_point(field_mutable:e8.ProceduralObjectProto.id)
  return _internal_mutable_id();
}
inline const std::string& ProceduralObjectProto::_internal_id() const {
  return id_.Get();
}
inline void ProceduralObjectProto::_internal_set_id(const std::string& value) {
  
  id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ProceduralObjectProto::set_id(std::string&& value) {
  
  id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:e8.ProceduralObjectProto.id)
}
inline void ProceduralObjectProto::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:e8.ProceduralObjectProto.id)
}
inline void ProceduralObjectProto::set_id(const char* value,
    size_t size) {
  
  id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:e8.ProceduralObjectProto.id)
}
inline std::string* ProceduralObjectProto::_internal_mutable_id() {
  
  return id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ProceduralObjectProto::release_id() {
  // @@protoc_insertion_point(field_release:e8.ProceduralObjectProto.id)
  return id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ProceduralObjectProto::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:e8.ProceduralObjectProto.id)
}
inline std::string* ProceduralObjectProto::unsafe_arena_release_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:e8.ProceduralObjectProto.id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ProceduralObjectProto::unsafe_arena_set_allocated_id(
    std::string* id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (id != nullptr) {
    
  } else {
    
  }
  id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:e8.ProceduralObjectProto.id)
}

// string name = 2;
inline void ProceduralObjectProto::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ProceduralObjectProto::name() const {
  // @@protoc_insertion_point(field_get:e8.ProceduralObjectProto.name)
  return _internal_name();
}
inline void ProceduralObjectProto::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:e8.ProceduralObjectProto.name)
}
inline std::string* ProceduralObjectProto::mutable_name() {
  // @@protoc_insertion_point(field_mutable:e8.ProceduralObjectProto.name)
  return _internal_mutable_name();
}
inline const std::string& ProceduralObjectProto::_internal_name() const {
  return name_.Get();
}
inline void ProceduralObjectProto::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ProceduralObjectProto::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:e8.ProceduralObjectProto.name)
}
inline void ProceduralObjectProto::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:e8.ProceduralObjectProto.name)
}
inline void ProceduralObjectProto::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:e8.ProceduralObjectProto.name)
}
inline std::string* ProceduralObjectProto::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ProceduralObjectProto::release_name() {
  // @@protoc_insertion_point(field_release:e8.ProceduralObjectProto.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ProceduralObjectProto::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:e8.ProceduralObjectProto.name)
}
inline std::string* ProceduralObjectProto::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:e8.ProceduralObjectProto.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ProceduralObjectProto::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:e8.ProceduralObjectProto.name)
}

// .e8.ProceduralObjectProto.ProceduralObjectType type = 3;
inline void ProceduralObjectProto::clear_type() {
  type_ = 0;
}
inline ::e8::ProceduralObjectProto_ProceduralObjectType ProceduralObjectProto::_internal_type() const {
  return static_cast< ::e8::ProceduralObjectProto_ProceduralObjectType >(type_);
}
inline ::e8::ProceduralObjectProto_ProceduralObjectType ProceduralObjectProto::type() const {
  // @@protoc_insertion_point(field_get:e8.ProceduralObjectProto.type)
  return _internal_type();
}
inline void ProceduralObjectProto::_internal_set_type(::e8::ProceduralObjectProto_ProceduralObjectType value) {
  
  type_ = value;
}
inline void ProceduralObjectProto::set_type(::e8::ProceduralObjectProto_ProceduralObjectType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:e8.ProceduralObjectProto.type)
}

// bool movable = 4;
inline void ProceduralObjectProto::clear_movable() {
  movable_ = false;
}
inline bool ProceduralObjectProto::_internal_movable() const {
  return movable_;
}
inline bool ProceduralObjectProto::movable() const {
  // @@protoc_insertion_point(field_get:e8.ProceduralObjectProto.movable)
  return _internal_movable();
}
inline void ProceduralObjectProto::_internal_set_movable(bool value) {
  
  movable_ = value;
}
inline void ProceduralObjectProto::set_movable(bool value) {
  _internal_set_movable(value);
  // @@protoc_insertion_point(field_set:e8.ProceduralObjectProto.movable)
}

// repeated .e8.ProceduralShapeProto shapes = 5;
inline int ProceduralObjectProto::_internal_shapes_size() const {
  return shapes_.size();
}
inline int ProceduralObjectProto::shapes_size() const {
  return _internal_shapes_size();
}
inline ::e8::ProceduralShapeProto* ProceduralObjectProto::mutable_shapes(int index) {
  // @@protoc_insertion_point(field_mutable:e8.ProceduralObjectProto.shapes)
  return shapes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::ProceduralShapeProto >*
ProceduralObjectProto::mutable_shapes() {
  // @@protoc_insertion_point(field_mutable_list:e8.ProceduralObjectProto.shapes)
  return &shapes_;
}
inline const ::e8::ProceduralShapeProto& ProceduralObjectProto::_internal_shapes(int index) const {
  return shapes_.Get(index);
}
inline const ::e8::ProceduralShapeProto& ProceduralObjectProto::shapes(int index) const {
  // @@protoc_insertion_point(field_get:e8.ProceduralObjectProto.shapes)
  return _internal_shapes(index);
}
inline ::e8::ProceduralShapeProto* ProceduralObjectProto::_internal_add_shapes() {
  return shapes_.Add();
}
inline ::e8::ProceduralShapeProto* ProceduralObjectProto::add_shapes() {
  // @@protoc_insertion_point(field_add:e8.ProceduralObjectProto.shapes)
  return _internal_add_shapes();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::e8::ProceduralShapeProto >&
ProceduralObjectProto::shapes() const {
  // @@protoc_insertion_point(field_list:e8.ProceduralObjectProto.shapes)
  return shapes_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace e8

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::e8::ProceduralObjectProto_ProceduralObjectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::e8::ProceduralObjectProto_ProceduralObjectType>() {
  return ::e8::ProceduralObjectProto_ProceduralObjectType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_procedural_5fobject_2eproto
